# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91117db8bc9cd57b56d93b140cf27dc6adb84eb17c31cc9a0a750b7acf7709bd3eb600229c7a117e344a5982803c2bf6a000b9b69f0730af5f0bfc7e773bbacd

test:
  secret_key_base: 4ec0a99835fe036dd95561fd833789da5021f42c8a851e90121fa7f60dbde31c869c319c569b244ede5ac063cdf62f08be04106a87b5976a478ec05450629e6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
