# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago'}, { name: 'Copenhagen'}])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Question.delete_all
Question.create([
  {question: 'What is your number one goal this year?', show_month: 1, show_day: 1},
  {question: 'What are you most grateful for?', show_month: 1, show_day: 2},
  {question: 'Are you content?', show_month: 1, show_day: 3},
  {question: 'What is your best memory of last year?', show_month: 1, show_day: 4},
  {question: 'What was the last major accomplishment you had?', show_month: 1, show_day: 5},
  {question: 'What possession could you not live without?', show_month: 1, show_day: 6},
  {question: 'Can people change?', show_month: 1, show_day: 7},
  {question: 'What is the last “good” thing you ate?', show_month: 1, show_day: 8},
  {question: 'What is your current favorite snack?', show_month: 1, show_day: 9},
  {question: 'What made you smile today?', show_month: 1, show_day: 10},
  {question: 'What’s your favorite accessory?', show_month: 1, show_day: 11},
  {question: 'What is making you mad?', show_month: 1, show_day: 12},
  {question: 'What did you have for dinner today?', show_month: 1, show_day: 13},
  {question: 'What did you get done?', show_month: 1, show_day: 14},
  {question: 'Who last called you on the phone?', show_month: 1, show_day: 15},
  {question: 'Who are you in love with?', show_month: 1, show_day: 16},
  {question: 'What are you grateful for?', show_month: 1, show_day: 17},
  {question: 'The best part of today was …', show_month: 1, show_day: 18},
  {question: 'My current favorite website is …', show_month: 1, show_day: 19},
  {question: 'What was the hardest thing you’re dealing with?', show_month: 1, show_day: 20},
  {question: 'Today I wish I had more …', show_month: 1, show_day: 21},
  {question: 'Tomorrow will be better because...', show_month: 1, show_day: 22},
  {question: 'What made today unusual?', show_month: 1, show_day: 23},
  {question: 'What are you looking for from life?', show_month: 1, show_day: 24},
  {question: 'What is your favorite thing to drink?', show_month: 1, show_day: 25},
  {question: 'Today the temperature was …', show_month: 1, show_day: 26},
  {question: 'How much did you spend at the grocery store the last time you went?', show_month: 1, show_day: 27},
  {question: 'Tomorrow I will...', show_month: 1, show_day: 28},
  {question: 'What was your last major purchase?', show_month: 1, show_day: 29},
  {question: 'My house is a home because...', show_month: 1, show_day: 30},
  {question: 'Who is the last person to tell you they loved you?', show_month: 1, show_day: 31},
  {question: 'What is your favorite piece of art you own?', show_month: 2, show_day: 1},
  {question: 'The most expensive bill I paid last month was …', show_month: 2, show_day: 2},
  {question: 'What’s the last thing you apologized for?', show_month: 2, show_day: 3},
  {question: 'My favorite color is …', show_month: 2, show_day: 4},
  {question: 'On a scale of 1-10 how is your health?', show_month: 2, show_day: 5},
  {question: 'If you could do today over, would you change anything?', show_month: 2, show_day: 6},
  {question: 'Name a person you wish you didn’t have to deal with today', show_month: 2, show_day: 7},
  {question: 'What is the largest TV screen in your house?', show_month: 2, show_day: 8},
  {question: 'What time did you go to bed last night?', show_month: 2, show_day: 9},
  {question: 'What did you buy today?', show_month: 2, show_day: 10},
  {question: 'I wish I had …', show_month: 2, show_day: 11},
  {question: 'How many photos did you take today?', show_month: 2, show_day: 12},
  {question: 'What book are you reading right now?', show_month: 2, show_day: 13},
  {question: 'How many hours of sleep did you get last night?', show_month: 2, show_day: 14},
  {question: 'Last thing you wanted but didn’t get', show_month: 2, show_day: 15},
  {question: 'What mood were you in today?', show_month: 2, show_day: 16},
  {question: 'What was the last new thing you tried?', show_month: 2, show_day: 17},
  {question: 'My biggest hope is …', show_month: 2, show_day: 18},
  {question: 'What has challenged your morals?', show_month: 2, show_day: 19},
  {question: 'What kind of car are you driving?', show_month: 2, show_day: 20},
  {question: 'List your pets', show_month: 2, show_day: 21},
  {question: 'What are three things you need to buy?', show_month: 2, show_day: 22},
  {question: 'Today I felt really secure knowing …', show_month: 2, show_day: 23},
  {question: 'Whose life did you make a difference in today?', show_month: 2, show_day: 24},
  {question: 'What is your super power?', show_month: 2, show_day: 25},
  {question: 'What is annoying you?', show_month: 2, show_day: 26},
  {question: 'What would have made today perfect?', show_month: 2, show_day: 27},
  {question: 'What stresses you?', show_month: 2, show_day: 28},
  {question: 'What did you do to take advantage of this extra day this year?', show_month: 2, show_day: 29},
  {question: 'What was the funniest thing you heard today?', show_month: 3, show_day: 1},
  {question: 'If you could have a new talent what would you want?', show_month: 3, show_day: 2},
  {question: 'Who is your best friend but not your spouse/significant other?', show_month: 3, show_day: 3},
  {question: 'What do you wish you had left unsaid?', show_month: 3, show_day: 4},
  {question: 'What was the first thing you ate or drank today?', show_month: 3, show_day: 5},
  {question: 'Are you saving or spending?', show_month: 3, show_day: 6},
  {question: 'On a scale of 1-10 how clean is your house? (10 being the cleanest)', show_month: 3, show_day: 7},
  {question: 'What is the last song you listened to?', show_month: 3, show_day: 8},
  {question: 'What relaxes you?', show_month: 3, show_day: 9},
  {question: 'What is the most valuable thing you own?', show_month: 3, show_day: 10},
  {question: 'What did you find inspiring today?', show_month: 3, show_day: 11},
  {question: 'Are you happy?', show_month: 3, show_day: 12},
  {question: 'How much “me” time did you take today?', show_month: 3, show_day: 13},
  {question: 'List three things you have faith in.', show_month: 3, show_day: 14},
  {question: 'Who is the last person you said “I love you” to?', show_month: 3, show_day: 15},
  {question: 'Did you seize any opportunities?', show_month: 3, show_day: 16},
  {question: 'Where did you go today?', show_month: 3, show_day: 17},
  {question: 'What advice were you given?', show_month: 3, show_day: 18},
  {question: 'Today was …', show_month: 3, show_day: 19},
  {question: 'What are you glad you did today?', show_month: 3, show_day: 20},
  {question: 'When was your last vacation? Where did you go?', show_month: 3, show_day: 21},
  {question: 'The greatest wisdom comes from …', show_month: 3, show_day: 22},
  {question: 'Who is your hero and why?', show_month: 3, show_day: 23},
  {question: 'Where is your top dream vacation destination?', show_month: 3, show_day: 24},
  {question: 'If you could have read one person’s mind today, who would you choose?', show_month: 3, show_day: 25},
  {question: 'What was the easiest thing about today?', show_month: 3, show_day: 26},
  {question: 'Did you thank anyone today?', show_month: 3, show_day: 27},
  {question: 'Did you work hard today?', show_month: 3, show_day: 28},
  {question: 'What was in your post office box today?', show_month: 3, show_day: 29},
  {question: 'Today was a complete …', show_month: 3, show_day: 30},
  {question: 'What are you seeking?', show_month: 3, show_day: 31},
  {question: 'Did you make someone laugh today? Was it intentional?', show_month: 4, show_day: 1},
  {question: 'What makes you sad?', show_month: 4, show_day: 2},
  {question: 'Was today typical? Why/Why not?', show_month: 4, show_day: 3},
  {question: 'Who do you trust the most?', show_month: 4, show_day: 4},
  {question: 'What’s your next major deadline? What is it for?', show_month: 4, show_day: 5},
  {question: 'What did you have for breakfast today?', show_month: 4, show_day: 6},
  {question: 'Do you have any regrets today?', show_month: 4, show_day: 7},
  {question: 'How did you add art to your life today?', show_month: 4, show_day: 8},
  {question: '… makes me happy', show_month: 4, show_day: 9},
  {question: 'When is the last time you danced?', show_month: 4, show_day: 10},
  {question: 'List the people you live with.', show_month: 4, show_day: 11},
  {question: 'What fears did you have today?', show_month: 4, show_day: 12},
  {question: 'What did you forget?', show_month: 4, show_day: 13},
  {question: 'What is your favorite TV show?', show_month: 4, show_day: 14},
  {question: 'I have faith that …', show_month: 4, show_day: 15},
  {question: 'Who is the last person you kissed?', show_month: 4, show_day: 16},
  {question: 'What did you wear today?', show_month: 4, show_day: 17},
  {question: 'What is testing you?', show_month: 4, show_day: 18},
  {question: 'What’s the oldest thing you’re wearing today?', show_month: 4, show_day: 19},
  {question: 'List 5 things you should have done today.', show_month: 4, show_day: 20},
  {question: 'Where did you spend the most time today?', show_month: 4, show_day: 21},
  {question: 'Share a favorite quote.', show_month: 4, show_day: 22},
  {question: 'Who did you worry about today?', show_month: 4, show_day: 23},
  {question: 'Were you creative today? How?', show_month: 4, show_day: 24},
  {question: 'What is the next major purchase you need to make?', show_month: 4, show_day: 25},
  {question: 'What is the last thing that made you cry?', show_month: 4, show_day: 26},
  {question: 'Today was tough because...', show_month: 4, show_day: 27},
  {question: 'Who are you jealous of?', show_month: 4, show_day: 28},
  {question: 'Where do you want to go next?', show_month: 4, show_day: 29},
  {question: 'What did you read today?', show_month: 4, show_day: 30},
  {question: 'Who was kind to you today?', show_month: 5, show_day: 1},
  {question: 'Who is the last person you spoke with?', show_month: 5, show_day: 2},
  {question: 'What makes you feel alive?', show_month: 5, show_day: 3},
  {question: 'The store I frequent the most is …', show_month: 5, show_day: 4},
  {question: 'How did you relax today?', show_month: 5, show_day: 5},
  {question: 'Describe your favorite pair of shoes you own now.', show_month: 5, show_day: 6},
  {question: 'What rule had the most impact on your day?', show_month: 5, show_day: 7},
  {question: 'How many pairs of shoes do you own?', show_month: 5, show_day: 8},
  {question: 'Today I lost …', show_month: 5, show_day: 9},
  {question: 'I really wish …. hadn’t been invented.', show_month: 5, show_day: 10},
  {question: 'What’s the most expensive thing you own that you can carry?', show_month: 5, show_day: 11},
  {question: 'How much money is in your wallet right now?', show_month: 5, show_day: 12},
  {question: 'Why was today unique?', show_month: 5, show_day: 13},
  {question: 'What did you leave undone today?', show_month: 5, show_day: 14},
  {question: 'Today the weather was …', show_month: 5, show_day: 15},
  {question: 'What was in your email today?', show_month: 5, show_day: 16},
  {question: 'What do you wish you had said today?', show_month: 5, show_day: 17},
  {question: 'What was the biggest decision you made today?', show_month: 5, show_day: 18},
  {question: 'What are you waiting for?', show_month: 5, show_day: 19},
  {question: 'What is the prevailing truth about your day', show_month: 5, show_day: 20},
  {question: 'What is the last thing you settled for?', show_month: 5, show_day: 21},
  {question: 'Describe your day in a six word sentence', show_month: 5, show_day: 22},
  {question: 'What was the last thing that hurt you?', show_month: 5, show_day: 23},
  {question: 'Did you use your time wisely today?', show_month: 5, show_day: 24},
  {question: 'Did you have a dream last night? Describe it', show_month: 5, show_day: 25},
  {question: 'Where do you wish you were?', show_month: 5, show_day: 26},
  {question: 'What music did you hear today?', show_month: 5, show_day: 27},
  {question: 'What did you have the most fun doing today?', show_month: 5, show_day: 28},
  {question: 'What do you love most about what you get to do every day?', show_month: 5, show_day: 29},
  {question: 'What hobbies do you have?', show_month: 5, show_day: 30},
  {question: 'What was the lowest point of your day?', show_month: 5, show_day: 31},
  {question: 'List the credit cards in your wallet.', show_month: 6, show_day: 1},
  {question: 'How close to perfect was today?', show_month: 6, show_day: 2},
  {question: 'When did you last sing out loud?', show_month: 6, show_day: 3},
  {question: 'What was the last gathering you attended?', show_month: 6, show_day: 4},
  {question: 'Did anything make you sad today?', show_month: 6, show_day: 5},
  {question: 'Share a secret thought', show_month: 6, show_day: 6},
  {question: 'List 5 things you wish you invented', show_month: 6, show_day: 7},
  {question: 'What’s the last recipe you prepared?', show_month: 6, show_day: 8},
  {question: 'Who is your most reliable friend?', show_month: 6, show_day: 9},
  {question: 'What made you lose track of time today?', show_month: 6, show_day: 10},
  {question: 'What are you confident about?', show_month: 6, show_day: 11},
  {question: 'How did you do it?', show_month: 6, show_day: 12},
  {question: 'What is the last purchase you made?', show_month: 6, show_day: 13},
  {question: 'Did you show someone appreciation today?', show_month: 6, show_day: 14},
  {question: 'How many push-ups can you do?', show_month: 6, show_day: 15},
  {question: 'What are you looking forward to?', show_month: 6, show_day: 16},
  {question: 'What is your favorite dish to prepare?', show_month: 6, show_day: 17},
  {question: 'There is no such thing as too much …', show_month: 6, show_day: 18},
  {question: 'What is the most important thing you were told today?', show_month: 6, show_day: 19},
  {question: 'What was the last thing you thought about today?', show_month: 6, show_day: 20},
  {question: 'What is the last book you read?', show_month: 6, show_day: 21},
  {question: 'What matters today?', show_month: 6, show_day: 22},
  {question: 'What project are you working on?', show_month: 6, show_day: 23},
  {question: 'What is your favorite color?', show_month: 6, show_day: 24},
  {question: 'What is your most prized possession?', show_month: 6, show_day: 25},
  {question: 'Were you ‘good’ or ‘bad’ today?', show_month: 6, show_day: 26},
  {question: 'What is the smartest thing you did today?', show_month: 6, show_day: 27},
  {question: 'What was in your mailbox today?', show_month: 6, show_day: 28},
  {question: 'Today I was so …', show_month: 6, show_day: 29},
  {question: 'The last thing I bought myself was …', show_month: 6, show_day: 30},
  {question: 'Were you alone today?', show_month: 7, show_day: 1},
  {question: 'Who was the last person you saw today?', show_month: 7, show_day: 2},
  {question: 'What do you need to let go of?', show_month: 7, show_day: 3},
  {question: 'What movie are you looking forward to?', show_month: 7, show_day: 4},
  {question: 'I just can’t …', show_month: 7, show_day: 5},
  {question: 'Who did you text today?', show_month: 7, show_day: 6},
  {question: 'Have you played the lottery?', show_month: 7, show_day: 7},
  {question: 'A funny thing happened on the way to …', show_month: 7, show_day: 8},
  {question: 'Name one thing you should toss right now, but just can’t', show_month: 7, show_day: 9},
  {question: 'What recently happened that made you proud of yourself?', show_month: 7, show_day: 10},
  {question: 'Who did you see the most today?', show_month: 7, show_day: 11},
  {question: 'Who inspires you?', show_month: 7, show_day: 12},
  {question: 'How much is gasoline per gallon?', show_month: 7, show_day: 13},
  {question: 'What was your horoscope today? Was it accurate?', show_month: 7, show_day: 14},
  {question: 'What are you most afraid of?', show_month: 7, show_day: 15},
  {question: 'What’s the biggest thing you have going on?', show_month: 7, show_day: 16},
  {question: 'What did you accomplish today?', show_month: 7, show_day: 17},
  {question: 'Did you act your age today?', show_month: 7, show_day: 18},
  {question: 'How busy was your day today?', show_month: 7, show_day: 19},
  {question: 'Did you see the sunrise or sunset today? How was it?', show_month: 7, show_day: 20},
  {question: 'What is your address?', show_month: 7, show_day: 21},
  {question: 'What do you wish there was less of in the world?', show_month: 7, show_day: 22},
  {question: 'What is stopping you?', show_month: 7, show_day: 23},
  {question: 'What were your chores today?', show_month: 7, show_day: 24},
  {question: 'What was the last thing that made you laugh out loud?', show_month: 7, show_day: 25},
  {question: 'Who did you eat dinner with?', show_month: 7, show_day: 26},
  {question: 'How did you make a difference in the world today?', show_month: 7, show_day: 27},
  {question: 'What is one thing you take with you everywhere?', show_month: 7, show_day: 28},
  {question: 'The last gift I’ve given was …', show_month: 7, show_day: 29},
  {question: 'What motivated you today?', show_month: 7, show_day: 30},
  {question: 'Who is your craziest friend?', show_month: 7, show_day: 31},
  {question: 'What did you have for lunch today?', show_month: 8, show_day: 1},
  {question: 'What did you let go of?', show_month: 8, show_day: 2},
  {question: 'What is the one thing you want to accomplish tomorrow?', show_month: 8, show_day: 3},
  {question: 'What was the last gift you gave?', show_month: 8, show_day: 4},
  {question: 'The last time I exercised was...', show_month: 8, show_day: 5},
  {question: 'What did you create today?', show_month: 8, show_day: 6},
  {question: 'What memories did you think about today?', show_month: 8, show_day: 7},
  {question: 'What is the last risk you took?', show_month: 8, show_day: 8},
  {question: 'What made you compromise?', show_month: 8, show_day: 9},
  {question: 'Who do you look up to?', show_month: 8, show_day: 10},
  {question: 'On a scale of 1-10 my day was a …', show_month: 8, show_day: 11},
  {question: 'What did the last text message you received say?', show_month: 8, show_day: 12},
  {question: 'Do you owe anyone money?', show_month: 8, show_day: 13},
  {question: 'What is your own favorite physical feature?', show_month: 8, show_day: 14},
  {question: 'What was the worst thing you ate today?', show_month: 8, show_day: 15},
  {question: 'I hope no one was looking when I …', show_month: 8, show_day: 16},
  {question: 'How many miles did you drive/ride/walk/run today?', show_month: 8, show_day: 17},
  {question: 'Who was the first person you saw today?', show_month: 8, show_day: 18},
  {question: 'What’s your biggest phobia?', show_month: 8, show_day: 19},
  {question: 'What was your first full thought this morning?', show_month: 8, show_day: 20},
  {question: 'How full is your fridge?', show_month: 8, show_day: 21},
  {question: 'What was the last healthy thing you did for yourself?', show_month: 8, show_day: 22},
  {question: 'What did you have to wait for today?', show_month: 8, show_day: 23},
  {question: 'What did you win?', show_month: 8, show_day: 24},
  {question: 'Who had the biggest influence on your day?', show_month: 8, show_day: 25},
  {question: 'What can you learn from today?', show_month: 8, show_day: 26},
  {question: 'What was the highest point of your day today?', show_month: 8, show_day: 27},
  {question: 'Did you pay it forward?', show_month: 8, show_day: 28},
  {question: 'What would you like to learn more about?', show_month: 8, show_day: 29},
  {question: 'What new TV show do you refuse to watch?', show_month: 8, show_day: 30},
  {question: 'How much is a gallon of milk?', show_month: 8, show_day: 31},
  {question: 'Who is the last person you spent quality time with?', show_month: 9, show_day: 1},
  {question: 'Who did you hug today?', show_month: 9, show_day: 2},
  {question: 'Describe your day in one word', show_month: 9, show_day: 3},
  {question: 'How are you?', show_month: 9, show_day: 4},
  {question: 'Did you do more talking or listening today?', show_month: 9, show_day: 5},
  {question: 'How much is a gallon of gas?', show_month: 9, show_day: 6},
  {question: 'What was the last stupid thing you did?', show_month: 9, show_day: 7},
  {question: 'What’s the next book you are going to read?', show_month: 9, show_day: 8},
  {question: 'What was the last mistake you made?', show_month: 9, show_day: 9},
  {question: 'What was the last gift you gave?', show_month: 9, show_day: 10},
  {question: 'What is your mission?', show_month: 9, show_day: 11},
  {question: 'If others described how you acted today in one word, it would be _________', show_month: 9, show_day: 12},
  {question: 'What is your current bank balance?', show_month: 9, show_day: 13},
  {question: 'Describe the last piece of furniture you purchased', show_month: 9, show_day: 14},
  {question: 'What time did you wake up this morning?', show_month: 9, show_day: 15},
  {question: 'Describe the last time you were embarrassed', show_month: 9, show_day: 16},
  {question: 'How did you improve yourself today?', show_month: 9, show_day: 17},
  {question: 'How much time did you spend outside today?', show_month: 9, show_day: 18},
  {question: 'In one year from today, what word do you hope best describes your life', show_month: 9, show_day: 19},
  {question: 'Who in your life is crazy talented? What is their talent?', show_month: 9, show_day: 20},
  {question: 'What do you wish there was more of in the world?', show_month: 9, show_day: 21},
  {question: 'My favorite sound is...', show_month: 9, show_day: 22},
  {question: 'What impact do you hope to have on the world?', show_month: 9, show_day: 23},
  {question: 'If you made laws, what one would you make today?', show_month: 9, show_day: 24},
  {question: 'Describe your last life-changing moment', show_month: 9, show_day: 25},
  {question: 'What opportunity are you waiting for?', show_month: 9, show_day: 26},
  {question: 'How many emails did you have today?', show_month: 9, show_day: 27},
  {question: 'What is the last movie you saw?', show_month: 9, show_day: 28},
  {question: 'Are you settling for something?', show_month: 9, show_day: 29},
  {question: 'What is standing in your way?', show_month: 9, show_day: 30},
  {question: 'What was the happiest headline in the news today?', show_month: 9, show_day: 31},
  {question: 'What did you have for lunch today?', show_month: 10, show_day: 1},
  {question: 'What is your dream pet?', show_month: 10, show_day: 2},
  {question: 'What is your favorite season?', show_month: 10, show_day: 3},
  {question: 'If you could share one thing with the world, what would it be?', show_month: 10, show_day: 4},
  {question: 'What would you do differently if you knew no one would judge you?', show_month: 10, show_day: 5},
  {question: 'Are you holding on to something you need to let go of?', show_month: 10, show_day: 6},
  {question: 'What have you done lately that you want to remember forever?', show_month: 10, show_day: 7},
  {question: 'What should you have for dinner next year?', show_month: 10, show_day: 8},
  {question: 'What is your dream job?', show_month: 10, show_day: 9},
  {question: 'When was the last time you really cried? Why?', show_month: 10, show_day: 10},
  {question: 'What do you hope to do by the time you are 90?', show_month: 10, show_day: 11},
  {question: 'Do you ask enough questions or do you settle for what you know?', show_month: 10, show_day: 12},
  {question: 'How do you reward yourself?', show_month: 10, show_day: 13},
  {question: 'When was the last time you tried something new?', show_month: 10, show_day: 14},
  {question: 'What is your idea of a perfect day?', show_month: 10, show_day: 15},
  {question: 'If you could do one thing over again, what would you change?', show_month: 10, show_day: 16},
  {question: 'If you had to teach something, what would you teach?', show_month: 10, show_day: 17},
  {question: 'Which is more important to you today?  Time or money?', show_month: 10, show_day: 18},
  {question: 'If you died tomorrow, what would you regret not doing?', show_month: 10, show_day: 19},
  {question: 'What are you avoiding?', show_month: 10, show_day: 20},
  {question: 'What do you most connect with? Why?', show_month: 10, show_day: 21},
  {question: 'What risk would you take if you knew you could not fail?', show_month: 10, show_day: 22},
  {question: 'What are you committed to?', show_month: 10, show_day: 23},
  {question: 'Which worries you more – doing things right or doing the right things?', show_month: 10, show_day: 24},
  {question: 'Do any of the things that used to upset you a few years ago matter at all today? What’s changed?', show_month: 10, show_day: 25},
  {question: 'What is one reminder you want to give yourself in one year?', show_month: 10, show_day: 26},
  {question: ' Would you rather have less work to do or more work you enjoy doing?', show_month: 10, show_day: 27},
  {question: 'What is the last song you listened to?', show_month: 10, show_day: 28},
  {question: 'What more should you be doing?', show_month: 10, show_day: 29},
  {question: 'How can you be more efficient?', show_month: 10, show_day: 30},
  {question: 'Who should you thank?', show_month: 10, show_day: 31},
  {question: 'What decision are you glad you made?', show_month: 11, show_day: 1},
  {question: 'Share some good advice', show_month: 11, show_day: 2},
  {question: 'What occupied your mind today?', show_month: 11, show_day: 3},
  {question: 'What was the best conversation you had today?', show_month: 11, show_day: 4},
  {question: 'Do you love your job?', show_month: 11, show_day: 5},
  {question: 'If you could get rid of one of your habits, what would it be?', show_month: 11, show_day: 6},
  {question: 'List 5 things you wish you had with you today', show_month: 11, show_day: 7},
  {question: 'What are the achievements you are most proud of?', show_month: 11, show_day: 8},
  {question: 'What gadgets did you use today?', show_month: 11, show_day: 9},
  {question: 'What shocked you?', show_month: 11, show_day: 10},
  {question: 'What was the last lie you told?', show_month: 11, show_day: 11},
  {question: 'What is your favorite cuisine?', show_month: 11, show_day: 12},
  {question: 'What do you have too much of?', show_month: 11, show_day: 13},
  {question: 'What do you want to tell yourself in one year?', show_month: 11, show_day: 14},
  {question: 'What is your greatest strength?', show_month: 11, show_day: 15},
  {question: 'Other than your clothes, what was with you the majority of the day?', show_month: 11, show_day: 16},
  {question: 'What’s your guilty pleasure?', show_month: 11, show_day: 17},
  {question: 'What is bothering you?', show_month: 11, show_day: 18},
  {question: 'What inspires you?', show_month: 11, show_day: 19},
  {question: 'What impression did you make on others today?', show_month: 11, show_day: 20},
  {question: 'What did you give up on today?', show_month: 11, show_day: 21},
  {question: 'How did you play today?', show_month: 11, show_day: 22},
  {question: 'How do you know?', show_month: 11, show_day: 23},
  {question: 'Name the last three things you used today', show_month: 11, show_day: 24},
  {question: 'What sound do you hate hearing?', show_month: 11, show_day: 25},
  {question: 'Do you feel appreciated?', show_month: 11, show_day: 26},
  {question: 'My body is …', show_month: 11, show_day: 27},
  {question: 'Today I had too much …', show_month: 11, show_day: 28},
  {question: 'What worries you?', show_month: 11, show_day: 29},
  {question: 'What did you get to do today?', show_month: 11, show_day: 30},
  {question: 'What is one thing you want to do by the end of the year?', show_month: 12, show_day: 1},
  {question: 'I really wish...', show_month: 12, show_day: 2},
  {question: 'Who is the first person you saw today?', show_month: 12, show_day: 3},
  {question: 'What memory do you want to keep from today?', show_month: 12, show_day: 4},
  {question: 'How much money is in your wallet?', show_month: 12, show_day: 5},
  {question: 'What makes you sweat?', show_month: 12, show_day: 6},
  {question: 'What do you wish your job was?', show_month: 12, show_day: 7},
  {question: 'What relationship did you nurture today?', show_month: 12, show_day: 8},
  {question: 'What are you passionate about?', show_month: 12, show_day: 9},
  {question: 'I realize tomorrow …', show_month: 12, show_day: 10},
  {question: 'Are you holding a grudge?', show_month: 12, show_day: 11},
  {question: 'What was weird about your day?', show_month: 12, show_day: 12},
  {question: 'How much of your day did you spend completely alone?', show_month: 12, show_day: 13},
  {question: 'How are you expanding your mind?', show_month: 12, show_day: 14},
  {question: 'What word are you using too much lately?', show_month: 12, show_day: 15},
  {question: 'How was your day today?', show_month: 12, show_day: 16},
  {question: 'What was the first thing you saw when you woke up this morning?', show_month: 12, show_day: 17},
  {question: 'What are three things you need to do tomorrow?', show_month: 12, show_day: 18},
  {question: 'What is the last place you visited online?', show_month: 12, show_day: 19},
  {question: 'Today I chose to...', show_month: 12, show_day: 20},
  {question: 'Were you a positive or negative person today?', show_month: 12, show_day: 21},
  {question: 'Who is the strongest person you know?', show_month: 12, show_day: 22},
  {question: 'Who do you wish had been a part of your day?', show_month: 12, show_day: 23},
  {question: 'What is one thing you were told today that you don’t want to forget?', show_month: 12, show_day: 24},
  {question: 'What was your weakness today?', show_month: 12, show_day: 25},
  {question: 'The music genre I listen to the most is...', show_month: 12, show_day: 26},
  {question: 'How much did you eat today?', show_month: 12, show_day: 27},
  {question: 'What’s worth fighting for?', show_month: 12, show_day: 28},
  {question: 'Today I felt …', show_month: 12, show_day: 29},
  {question: 'Did you smile or frown more today?', show_month: 12, show_day: 30},
  {question: 'What improvements are you making?', show_month: 12, show_day: 31}
])
