# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Question.delete_all
# Question.create([
#   {question:'What did you have for lunch today?', show_month: 8, show_day: 1},
#   {question:'What did you let go of?', show_month: 8, show_day: 2},
#   {question:'What is the one thing you want to accomplish tomorrow?', show_month: 8, show_day: 3},
#   {question:'What was the last gift you gave?', show_month: 8, show_day: 4},
#   {question:'The last time I exercised was...', show_month: 8, show_day: 5},
#   {question:'What did you create today?', show_month: 8, show_day: 6},
#   {question:'What memories did you think about today?', show_month: 8, show_day: 7},
#   {question:'What is the last risk you took?', show_month: 8, show_day: 8},
#   {question:'What made you compromise?', show_month: 8, show_day: 9},
#   {question:'Who do you look up to?', show_month: 8, show_day: 10},
#   {question:'On a scale of 1-10 my day was a …', show_month: 8, show_day: 11},
#   {question:'What did the last text message you received say?', show_month: 8, show_day: 12},
#   {question:'Do you owe anyone money?', show_month: 8, show_day: 13},
#   {question:'What is your own favorite physical feature?', show_month: 8, show_day: 14},
#   {question:'What was the worst thing you ate today?', show_month: 8, show_day: 15},
#   {question:'I hope no one was looking when I …', show_month: 8, show_day: 16},
#   {question:'How many miles did you drive/ride/walk/run today?', show_month: 8, show_day: 17},
#   {question:'Who was the first person you saw today?', show_month: 8, show_day: 18},
#   {question:'What’s your biggest phobia?', show_month: 8, show_day: 19},
#   {question:'What was your first full thought this morning?', show_month: 8, show_day: 20},
#   {question:'How full is your fridge?', show_month: 8, show_day: 21},
#   {question:'What was the last healthy thing you did for yourself?', show_month: 8, show_day: 22},
#   {question:'What did you have to wait for today?', show_month: 8, show_day: 23},
#   {question:'What did you win?', show_month: 8, show_day: 24},
#   {question:'Who had the biggest influence on your day?', show_month: 8, show_day: 25},
#   {question:'What can you learn from today?', show_month: 8, show_day: 26},
#   {question:'What was the highest point of your day today?', show_month: 8, show_day: 27},
#   {question:'Did you pay it forward?', show_month: 8, show_day: 28},
#   {question:'What would you like to learn more about?', show_month: 8, show_day: 29},
#   {question:'What new TV show do you refuse to watch?', show_month: 8, show_day: 30},
#   {question:'How much is a gallon of milk?', show_month: 8, show_day: 31},
#   {question:'What is your number one goal this year?', show_month: 1, show_day: 1},
#   {question:'What are you most grateful for?', show_month: 1, show_day: 2},
#   {question:'Are you content?', show_month: 1, show_day: 3},
#   {question:'What is your best memory of last year?', show_month: 1, show_day: 4},
#   {question:'What was the last major accomplishment you had?', show_month: 1, show_day: 5},
#   {question:'What possession could you not live without?', show_month: 1, show_day: 6},
#   {question:'Can people change?', show_month: 1, show_day: 7},
#   {question:'What is the last “good” thing you ate?', show_month: 1, show_day: 8},
#   {question:'What is your current favorite snack?', show_month: 1, show_day: 9},
#   {question:'What made you smile today?', show_month: 1, show_day: 10},
#   {question:'What’s your favorite accessory?', show_month: 1, show_day: 11},
#   {question:'What is making you mad?', show_month: 1, show_day: 12},
#   {question:'What did you have for dinner today?', show_month: 1, show_day: 13},
#   {question:'What did you get done?', show_month: 1, show_day: 14},
#   {question:'Who last called you on the phone?', show_month: 1, show_day: 15},
#   {question:'Who are you in love with?', show_month: 1, show_day: 16},
#   {question:'What are you grateful for?', show_month: 1, show_day: 17},
#   {question:'The best part of today was …', show_month: 1, show_day: 18},
#   {question:'My current favorite website is …', show_month: 1, show_day: 19},
#   {question:'What was the hardest thing you’re dealing with?', show_month: 1, show_day: 20},
#   {question:'Today I wish I had more …', show_month: 1, show_day: 21},
#   {question:'Tomorrow will be better because...', show_month: 1, show_day: 22},
#   {question:'What made today unusual?', show_month: 1, show_day: 23},
#   {question:'What are you looking for from life?', show_month: 1, show_day: 24},
#   {question:'What is your favorite thing to drink?', show_month: 1, show_day: 25},
#   {question:'Today the temperature was …', show_month: 1, show_day: 26},
#   {question:'How much did you spend at the grocery store the last time you went?', show_month: 1, show_day: 27},
#   {question:'Tomorrow I will...', show_month: 1, show_day: 28},
#   {question:'What was your last major purchase?', show_month: 1, show_day: 29},
#   {question:'My house is a home because...', show_month: 1, show_day: 30},
#   {question:'Who is the last person to tell you they loved you?', show_month: 1, show_day: 31},
#   {question:'Who is the last person you spent quality time with?', show_month: 9, show_day: 1},
#   {question:'Who did you hug today?', show_month: 9, show_day: 2},
#   {question:'Describe your day in one word', show_month: 9, show_day: 3},
#   {question:'How are you?', show_month: 9, show_day: 4},
#   {question:'Did you do more talking or listening today?', show_month: 9, show_day: 5},
#   {question:'How much is a gallon of gas?', show_month: 9, show_day: 6},
#   {question:'What was the last stupid thing you did?', show_month: 9, show_day: 7},
#   {question:'What’s the next book you are going to read?', show_month: 9, show_day: 8},
#   {question:'What was the mistake?', show_month: 9, show_day: 9},
#   {question:'What was the last gift you gave?', show_month: 9, show_day: 10},
#   {question:'What is your mission?', show_month: 9, show_day: 11},
#   {question:'If others described how you acted today in one word, it would be...', show_month: 9, show_day: 12},
#   {question:'What is your current bank balance?', show_month: 9, show_day: 13},
#   {question:'Describe the last piece of furniture you purchased', show_month: 9, show_day: 14},
#   {question:'What time did you wake up this morning?', show_month: 9, show_day: 15},
#   {question:'Describe the last time you were embarrassed', show_month: 9, show_day: 16},
#   {question:'How did you improve yourself today?', show_month: 9, show_day: 17},
#   {question:'How much time did you spend outside today?', show_month: 9, show_day: 18},
#   {question:'In one year from today, what word do you hope best describes your life', show_month: 9, show_day: 19},
#   {question:'Who in your life is crazy talented? What is their talent?', show_month: 9, show_day: 20},
#   {question:'What do you wish there was more of in the world?', show_month: 9, show_day: 21},
#   {question:'My favorite sound is ...', show_month: 9, show_day: 22},
#   {question:'What impact do you hope to have on the world?', show_month: 9, show_day: 23},
#   {question:'If you made laws, what one would you make today?', show_month: 9, show_day: 24},
#   {question:'Describe your last life-changing moment', show_month: 9, show_day: 25},
#   {question:'What opportunity are you waiting for?', show_month: 9, show_day: 26},
#   {question:'How many emails did you have today?', show_month: 9, show_day: 27},
#   {question:'What is the last movie you saw?', show_month: 9, show_day: 28},
#   {question:'Are you settling for something?', show_month: 9, show_day: 29},
#   {question:'What is standing in your way?', show_month: 9, show_day: 30},
#   {question:'What was the happiest headline in the news today?', show_month: 9, show_day: 31}
# ])

Answer.delete_all
Answer.create([
  {answer: 'answer 1a', question:questions[94]},
  {answer: 'answer 1b', question:questions[94]},
  {answer: 'answer 1c', question:questions[94]},
  {answer: 'answer 1d', question:questions[94]},
  {answer: 'answer 2a', question:questions[95]},
  {answer: 'answer 2b', question:questions[95]},
  {answer: 'answer 2c', question:questions[95]},
  {answer: 'answer 2d', question:questions[95]}
])
